---
all:
  hosts:
    localhost:
      ansible_user: vagrant
      ansible_port: "{{ lookup('env', 'VAGRANT_PORT') | int }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'VAGRANT_KEY') }}"
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
